apiVersion: apps/v1
kind: Deployment
metadata:
  name: brezyweather-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brezyweather
      version: '2.0'
  template:
    metadata:
      labels:
        app: brezyweather
        version: '2.0'
    spec:
      containers:
      - name: brezyweather
        image: codewithpraveen/labs-k8s-canary:2.0
        resources:
          limits:
            memory: 128Mi # MiB or Mebibytes
            cpu: 500m # millicores
        ports:
        - containerPort: 80